import HomeWrapper from "@/Components/HomeWrapper/HomeWrapper";
import HomeMenu from "@/Components/HomeMenu/HomeMenu";
import "./globals.scss";
import Fonts from "@/Components/Fonts/Fonts";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Fonts />
        <HomeWrapper>
          <HomeMenu />
          {children}
        </HomeWrapper>
      </body>
    </html>
  );
}
